name: food_service

services:
    database:
        image: postgres:latest
        container_name: postgres_service
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: test
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./src/sql/test.sql:/docker-entrypoint-initdb.d/init.sql
            - ./src/sql/tables.sql:/src/sql/tables.sql

volumes:
    postgres_data:
