name: CI Test

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres:15
                env:
                    POSTGRES_USER: user
                    POSTGRES_PASSWORD: password
                    POSTGRES_DB: test
                ports:
                    - 5432:5432
                options: >-
                    --health-cmd="pg_isready -U user" 
                    --health-interval=10s 
                    --health-timeout=5s 
                    --health-retries=5

        steps:
            - uses: actions/checkout@v4

            - name: "Set up Python"
              uses: actions/setup-python@v4
              with:
                  python-version: "3.11"

            - name: "Install dependencies"
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: "Wait for PostgreSQL to be ready"
              run: |
                  until pg_isready -h localhost -p 5432 -U user; do
                    sleep 1
                  done

            - name: "Initialize database with init.sql"
              run: |
                  psql postgresql://user:password@localhost:5432/test -f src/sql/test-ci.sql
                  psql postgresql://user:password@localhost:5432/test -f src/sql/tables.sql

            - name: "Run pytest"
              env:
                  ENV_PATH: .env.test
              run: |
                  pytest
